# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Codecado
tagline:             'Coffee. Code. Avocado.'
description:         'A Code Journal of Bravocado'
url:                 http://brv.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Bravocado
  url:               https://twitter.com/bravocado
  email:             bravocado.project@gmail.com

# Custom vars
version:             1.0.0
